### PR TITLE
chore(README.md): Add other relevant projects

### PR DESCRIPTION
**Pull request by cobraz**
Hello 👋

This pull request adds a new section to the `README.md` containing projects that utilize this package. Let there be no questions as to why I'm suggesting the change, I hope people find my `norwegian-ssn-graphql-scalar` project.

I've added some _marketing_ by adding Censorbot by Vipps and Angular code samples  as well.

### CODE REVIEW

**Comment by mikaello** [comment]
I like these sections, where you can point users to other usefull projects. This looks like a good start.

I think this section could be translated to a list, so it would be easier to add other good alternatives / related projects as they appear.

**Comment by cobraz** [comment]
Yeah, good idea. Let me test something out :)

**Comment by cobraz** [comment]
@mikaello What do you think about the changes?

**Comment by cobraz** [comment]
(also did some formatting)

**Comment by mikaello** [comment]
Perfect! Thanks :-)

**Pull request merged**
